name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CGO_ENABLED: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.0
          args: -E gofmt,goimports --timeout 5m0s

  targets:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.services.outputs.services }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: services
        name: Get services
        run: echo "services=$(ls -1 cmd | tr '\n' ',' | sed 's/,$//' | jq -csR 'split(",")')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.targets.outputs.services) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Generate .goreleaser.yaml
        run: |
          SERVICE_NAME=${{ matrix.target }} envsubst < .goreleaser.yaml > .goreleaser.${{ matrix.target }}.yaml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot -f .goreleaser.${{ matrix.target }}.yaml
