name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CGO_ENABLED: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.0
          args: -E gofmt,goimports --timeout 5m0s

  targets:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.services.outputs.services }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: services
        name: Get services
        run: echo "services=$(ls -1 cmd | tr '\n' ',' | sed 's/,$//' | jq -csR 'split(",")')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.targets.outputs.services) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Build
        run: go build -o dist/${{ matrix.target }} ./cmd/${{ matrix.target }}
      - run: which envsubst

  debug:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.targets.outputs.services) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo ${{ matrix.target }}
