name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  CGO_ENABLED: 0

jobs:
  targets:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.services.outputs.services }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: services
        name: Get services
        run: echo "services=$(ls -1 cmd | tr '\n' ',' | sed 's/,$//' | jq -csR 'split(\',\')')" >> $GITHUB_OUTPUT

  debug:
    runs-on: ubuntu-latest
    needs: targets
    strategy:
      matrix:
        target: ${{ fromJson(needs.targets.outputs.services) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo ${{ matrix.target }}

