name: release

on:
  push:
    tags:
      - '*/v*.*.*'

jobs:
  target:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.service.outputs.service }}
      version: ${{ steps.service.outputs.version }}
    steps:
      - id: service
        name: Get service
        run: |
          echo "service=$(echo ${GITHUB_REF#refs/tags/} | cut -d'/' -f1)" >> $GITHUB_OUTPUT
          echo "version=$(echo ${GITHUB_REF#refs/tags/} | cut -d'/' -f2)" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: target
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate .goreleaser.yaml
        run: |
          SERVICE_NAME=${{ needs.target.outputs.service }} envsubst < .goreleaser.yaml > .goreleaser.${{ needs.target.outputs.service }}.yaml
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean -f .goreleaser.${{ needs.target.outputs.service }}.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.target.outputs.version }}
